spring:
   application:
    name: sample rest application
   datasource:
    url: jdbc:postgresql://localhost:5432/mylocal?currentSchema=shaileshtest
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
   http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
   
   jackson:
    serialization:
      write-dates-as-timestamps: false
   
   myapp:
    usenewval: false
    newval: hello
    oldval: world.....